#!/usr/bin/env bash
#
# live_selftest.sh - run the Phase-3 -live build in the headless Strategy Tester with InpLiveMode=true
# (the file-queue decision path) against an isolated queue root, then summarise the queue.
#
#   ./live_selftest.sh --symbol EURUSD.dk --from 2024.01.01 --to 2024.06.30            # no driver: implicit delays -> code 8
#   ./live_selftest.sh --symbol EURUSD.dk --from 2024.01.01 --to 2024.06.30 --selftest # in-EA scripted task driver (Slice 6)
#
# Flags: --symbol S --from D --to D --model N(4) --timeout S --root NAME(live_selftest) --selftest
#        --poll S(30) --beat S(600) --maxage N(3) --keep (do not wipe the queue root first)
set -euo pipefail
MT5_DATA="/mnt/c/Users/jacks/AppData/Roaming/MetaQuotes/Terminal/EE0304F13905552AE0B5EAEFB04866EB"
MT5_DATA_WIN='C:\Users\jacks\AppData\Roaming\MetaQuotes\Terminal\EE0304F13905552AE0B5EAEFB04866EB'
TERMINAL="/mnt/c/Program Files/OANDA MetaTrader 5/terminal64.exe"
COMMON="/mnt/c/Users/jacks/AppData/Roaming/MetaQuotes/Terminal/Common/Files"
SETDIR="$MT5_DATA/MQL5/Profiles/Tester"
INI_WSL="$MT5_DATA/hft_live.ini"; INI_WIN="$MT5_DATA_WIN\\hft_live.ini"
SYMBOL="EURUSD.dk"; FROM="2024.01.01"; TO="2024.06.30"; MODEL=4; TIMEOUT=3600
ROOT="live_selftest"; SELFTEST=false; POLL=30; BEAT=600; MAXAGE=3; KEEP=false
log(){ printf '%s\n' "$*" >&2; }; die(){ printf 'ERROR: %s\n' "$*" >&2; exit 1; }
while [[ $# -gt 0 ]]; do case "$1" in
  --symbol) SYMBOL="$2"; shift 2;; --from) FROM="$2"; shift 2;; --to) TO="$2"; shift 2;;
  --model) MODEL="$2"; shift 2;; --timeout) TIMEOUT="$2"; shift 2;; --root) ROOT="$2"; shift 2;;
  --selftest) SELFTEST=true; shift;; --poll) POLL="$2"; shift 2;; --beat) BEAT="$2"; shift 2;;
  --maxage) MAXAGE="$2"; shift 2;; --keep) KEEP=true; shift;;
  -h|--help) sed -n '3,11p' "$0"; exit 0;; *) die "unknown flag: $1";; esac; done
[[ -x "$TERMINAL" ]] || die "terminal64 not found"
[[ -f "$MT5_DATA/MQL5/Experts/HybridForwardTest-live.ex5" ]] || die "HybridForwardTest-live.ex5 not compiled/deployed"
proc_running(){ tasklist.exe /FI "IMAGENAME eq terminal64.exe" 2>/dev/null | grep -qi terminal64.exe; }
proc_running && die "terminal64 already running - refusing to launch (would disrupt the user)."
QROOT="$COMMON/$ROOT"
if ! $KEEP; then rm -rf "$QROOT"; log "wiped queue root $QROOT"; fi
mkdir -p "$SETDIR"
{
  echo "InpRiskPct=0.01"; echo "InpMagic=990217"
  echo "InpUseColoredDialog=false"; echo "InpAutoApprove=0"
  echo "InpLiveMode=true"; echo "InpLiveSelfTest=$SELFTEST"; echo "InpLiveRoot=$ROOT"
  echo "InpTaskPollSec=$POLL"; echo "InpHeartbeatSec=$BEAT"; echo "InpLiveMaxAgeBars=$MAXAGE"
  echo "InpUseSMC=true"; echo "InpUseFib=true"; echo "InpUseEMA=false"; echo "InpUseEMArevQ=true"; echo "InpUseTrendCont=true"
  echo "InpUseShock=false"; echo "InpUseEmaRevInv=false"
  echo "InpShotOnDecision=${SHOT_ON_DECISION:-false}"; echo "InpManagePanel=false"; echo "InpShowEvents=true"   # SHOT_ON_DECISION=true: also write the D1 + swing sidecars
} > "$SETDIR/hft_live.set"
{
  echo "; auto-generated by pipeline/live_selftest.sh"
  echo "[Tester]"; echo "Expert=HybridForwardTest-live"; echo "ExpertParameters=hft_live.set"
  echo "Symbol=$SYMBOL"; echo "Period=H4"; echo "Model=$MODEL"; echo "ExecutionMode=0"; echo "Optimization=0"
  echo "FromDate=$FROM"; echo "ToDate=$TO"; echo "ForwardMode=0"; echo "Deposit=25000"; echo "Currency=USD"; echo "Leverage=100"
  echo "Visual=0"; echo "ReplaceReport=1"; echo "ShutdownTerminal=1"
} > "$INI_WSL"
log "[Tester] $SYMBOL H4 model=$MODEL $FROM..$TO  live root=$ROOT selftest=$SELFTEST poll=${POLL}s beat=${BEAT}s maxage=$MAXAGE"
START=$(date +%s)
nohup "$TERMINAL" "/config:$INI_WIN" >/dev/null 2>&1 &
sleep 10; proc_running && log "terminal64 running." || log "WARN: terminal64 not detected yet."
deadline=$(( START + TIMEOUT ))
while proc_running; do (( $(date +%s) >= deadline )) && { log "TIMEOUT - terminal still running"; break; }; sleep 5; done
log "tester finished in $(( $(date +%s) - START ))s"
# --- summary -----------------------------------------------------------------
log "===== queue root: $QROOT ====="
log "signals: $(ls "$QROOT/signals" 2>/dev/null | wc -l)   by status: $(grep -ho '"status":"[a-z_]*"' "$QROOT"/signals/*.json 2>/dev/null | sort | uniq -c | tr '\n' ' ')"
log "tasks pending: $(ls "$QROOT/tasks" 2>/dev/null | grep -c json || true)   done: $(ls "$QROOT/tasks/done" 2>/dev/null | wc -l)   acks: $(ls "$QROOT/acks" 2>/dev/null | wc -l)"
# live journals are MONTHLY (<SYM>_YYYYMM.csv, E3/§11-5): summarise across all months
JS=$(ls "$QROOT"/journal/${SYMBOL}_[0-9][0-9][0-9][0-9][0-9][0-9].csv 2>/dev/null || true)
if [[ -n "$JS" ]]; then
  log "journal months: $(echo "$JS" | xargs -n1 basename | tr '\n' ' ')"
  log "journal rows=$(cat $JS | grep -v '^signal_id' | wc -l)  decisions: $(cat $JS | awk -F, '!/^signal_id/{print $18}' | sort | uniq -c | tr '\n' ' ')  skip8=$(cat $JS | awk -F, '!/^signal_id/ && $18=="skipped" && $19==8' | wc -l)  live=1: $(cat $JS | awk -F, '!/^signal_id/ && $47==1' | wc -l)  auto=1: $(cat $JS | awk -F, '!/^signal_id/ && $51==1' | wc -l)"
else
  log "WARNING: no monthly live journal found under $QROOT/journal"
fi
DP=$(ls "$QROOT"/journal/${SYMBOL}_*.delays.csv 2>/dev/null | head -1 || true)
[[ -n "$DP" ]] && log "delays: rows=$(($(wc -l < "$DP")-1))  implicit=1: $(awk -F, 'NR>1 && $13==1' "$DP" | wc -l)  explicit: $(awk -F, 'NR>1 && $13==0' "$DP" | wc -l)"
log "heartbeat: $(cat "$QROOT"/heartbeat_${SYMBOL}.json 2>/dev/null | head -c 300)"
log "audit tail:"; { tail -8 "$QROOT/audit_${SYMBOL}.log" 2>/dev/null || true; } >&2
log "tmp leftovers: $(find "$QROOT" -name '*.tmp' 2>/dev/null | wc -l)"
