#!/usr/bin/env bash
#
# mt5_verify.sh - headless Strategy-Tester verification of HybridForwardTest.
#
# Launches terminal64 with a [Tester] config ini + a .set file that puts the
# harness in AUTO mode (InpAutoApprove) so the run completes with no modal, then
# the terminal self-closes (ShutdownTerminal=1) and we read the journal CSV.
#
#   ./mt5_verify.sh --mode ALL  --strat EMA           # exercise two-target lifecycle
#   ./mt5_verify.sh --mode SKIP --strat SMC,Fib,EMA   # per-strategy signal counts
#   ./mt5_verify.sh --mode SKIP --from 2022.01.01 --to 2024.12.31 --strat SMC
#
# Flags: --mode ALL|SKIP  --strat CSV(SMC,Fib,EMA)  --symbol S  --from D --to D
#        --model N (0 every-tick,1 1min-OHLC[default],4 real-ticks)  --timeout S
#
set -euo pipefail

MT5_DATA="/mnt/c/Users/jacks/AppData/Roaming/MetaQuotes/Terminal/EE0304F13905552AE0B5EAEFB04866EB"
MT5_DATA_WIN='C:\Users\jacks\AppData\Roaming\MetaQuotes\Terminal\EE0304F13905552AE0B5EAEFB04866EB'
TERMINAL="/mnt/c/Program Files/OANDA MetaTrader 5/terminal64.exe"
COMMON_JOURNAL="/mnt/c/Users/jacks/AppData/Roaming/MetaQuotes/Terminal/Common/Files/journal"
SETDIR="$MT5_DATA/MQL5/Profiles/Tester"
INI_WSL="$MT5_DATA/hft_verify.ini"
INI_WIN="$MT5_DATA_WIN\\hft_verify.ini"

MODE=ALL; STRAT="SMC,Fib,EMA"; SYMBOL="EURUSD.dk"
FROM="2023.01.01"; TO="2024.12.31"; MODEL=1; TIMEOUT=1800; FORCE_PENDING=false; FORCE_PTS=0
log(){ printf '%s\n' "$*" >&2; }
die(){ printf 'ERROR: %s\n' "$*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do case "$1" in
  --mode) MODE="$2"; shift 2;;
  --strat) STRAT="$2"; shift 2;;
  --symbol) SYMBOL="$2"; shift 2;;
  --from) FROM="$2"; shift 2;;
  --to) TO="$2"; shift 2;;
  --model) MODEL="$2"; shift 2;;
  --timeout) TIMEOUT="$2"; shift 2;;
  --force-pending) FORCE_PENDING=true; shift;;  # AA_ALL: place forced STOP pendings (verify fill-binding)
  --force-pending-pts) FORCE_PTS="$2"; shift 2;; # >0 stop (fills), <0 far limit (expires)
  -h|--help) sed -n '3,17p' "$0"; exit 0;;
  *) die "unknown flag: $1";;
esac; done
[[ -x "$TERMINAL" ]] || die "terminal64 not found"

case "$MODE" in ALL) AA=1;; SKIP) AA=2;; *) die "--mode must be ALL or SKIP";; esac
has(){ [[ ",$STRAT," == *",$1,"* ]] && echo true || echo false; }
USE_SMC=$(has SMC); USE_FIB=$(has Fib); USE_EMA=$(has EMA)

proc_running(){ tasklist.exe /FI "IMAGENAME eq terminal64.exe" 2>/dev/null | grep -qi terminal64.exe; }
proc_running && die "terminal64 already running - refusing to launch (would disrupt the user)."

# --- .set file (EA inputs) -------------------------------------------------
mkdir -p "$SETDIR"
{
  echo "InpRiskPct=0.01"
  echo "InpMagic=990217"
  echo "InpUseColoredDialog=false"
  echo "InpAutoApprove=$AA"
  echo "InpUseSMC=$USE_SMC"
  echo "InpUseFib=$USE_FIB"
  echo "InpUseEMA=$USE_EMA"
  $FORCE_PENDING && echo "InpForcePendingTest=true"
  $FORCE_PENDING && echo "InpForcePendingPts=$FORCE_PTS"
} > "$SETDIR/hft_verify.set"
log ".set -> AutoApprove=$AA SMC=$USE_SMC Fib=$USE_FIB EMA=$USE_EMA force_pending=$FORCE_PENDING"

# --- [Tester] config ini ---------------------------------------------------
{
  echo "; auto-generated by pipeline/mt5_verify.sh"
  echo "[Tester]"
  echo "Expert=HybridForwardTest"
  echo "ExpertParameters=hft_verify.set"
  echo "Symbol=$SYMBOL"
  echo "Period=H4"
  echo "Model=$MODEL"
  echo "ExecutionMode=0"
  echo "Optimization=0"
  echo "FromDate=$FROM"
  echo "ToDate=$TO"
  echo "ForwardMode=0"
  echo "Deposit=25000"
  echo "Currency=USD"
  echo "Leverage=100"
  echo "Visual=0"
  echo "ReplaceReport=1"
  echo "ShutdownTerminal=1"
} > "$INI_WSL"
log "[Tester] $SYMBOL H4 model=$MODEL $FROM..$TO"

# snapshot existing journals so we can find the new one
mkdir -p "$COMMON_JOURNAL"
BEFORE=$(ls -1 "$COMMON_JOURNAL" 2>/dev/null | sort || true)

# --- launch + wait ---------------------------------------------------------
log "launching tester ..."
START=$(date +%s)
nohup "$TERMINAL" "/config:$INI_WIN" >/dev/null 2>&1 &
sleep 10
proc_running && log "terminal64 running." || log "WARN: terminal64 not detected yet."
deadline=$(( START + TIMEOUT ))
while proc_running; do
  if (( $(date +%s) >= deadline )); then
    log "TIMEOUT ${TIMEOUT}s - terminal still running; leaving it for the operator."
    break
  fi
  sleep 5
done
ELAPSED=$(( $(date +%s) - START ))
log "tester finished in ${ELAPSED}s"

# --- locate + summarise the journal ---------------------------------------
AFTER=$(ls -1 "$COMMON_JOURNAL" 2>/dev/null | sort || true)
NEWJ=$(comm -13 <(printf '%s\n' "$BEFORE") <(printf '%s\n' "$AFTER") | grep -i "^${SYMBOL}_" | tail -1 || true)
[[ -z "$NEWJ" ]] && NEWJ=$(ls -t "$COMMON_JOURNAL"/${SYMBOL}_*.csv 2>/dev/null | head -1 | xargs -r basename)
[[ -n "$NEWJ" ]] || { log "NO journal produced - check tester ran (algo-trading enabled?)."; exit 1; }
JPATH="$COMMON_JOURNAL/$NEWJ"
log "journal: $JPATH"
log "----- per-strategy counts (journalled = arbitration winners) -----"
for s in SweepMSS DeepFib EMArev; do
  n=$(grep -c ",$s," "$JPATH" 2>/dev/null || echo 0)
  log "  $s: $n"
done
TOTAL=$(($(wc -l < "$JPATH")-1))
log "total journal rows: $TOTAL"
log "path for inspection: $JPATH"
