#!/usr/bin/env bash
#
# mt5_import.sh - unattended MT5 tick import driver (run from WSL).
#
# Stages one or more symbols' CSVs, writes a job list, launches the OANDA
# terminal64.exe headlessly with a /config startup ini that auto-attaches the
# AutoImport EA, waits for the terminal to import everything and self-close,
# then parses the status file and returns pass/fail.
#
#   ./mt5_import.sh AUDUSD                 # one symbol
#   ./mt5_import.sh AUDUSD NZDUSD USDCAD   # several (sequential, one terminal)
#   ./mt5_import.sh --clean AUDUSD ...     # delete staged CSV(s) after success
#   ./mt5_import.sh --host-symbol EURUSD.dk AUDUSD   # host chart symbol override
#   ./mt5_import.sh --timeout 3600 AUDUSD            # max wait seconds (default 2400)
#
# SAFETY: if a terminal64.exe is ALREADY running it refuses to launch (would
# disrupt the terminal the user may be using) and exits non-zero. The AutoImport
# EA closes the terminal itself when done; on timeout this script only reports
# (it does not force-kill) so the operator stays in control.
#
set -euo pipefail

REPO="/home/jack/hybrid_project"
MT5_DATA="/mnt/c/Users/jacks/AppData/Roaming/MetaQuotes/Terminal/EE0304F13905552AE0B5EAEFB04866EB"
MT5_DATA_WIN='C:\Users\jacks\AppData\Roaming\MetaQuotes\Terminal\EE0304F13905552AE0B5EAEFB04866EB'
TERMINAL="/mnt/c/Program Files/OANDA MetaTrader 5/terminal64.exe"
IMPORT_DIR="$MT5_DATA/MQL5/Files/import"
STAGE="$REPO/pipeline/stage_csv_for_import.sh"
INI_WSL="$MT5_DATA/autoimport_startup.ini"
INI_WIN="$MT5_DATA_WIN\\autoimport_startup.ini"
STATUS="$IMPORT_DIR/import_status.txt"
JOBS="$IMPORT_DIR/jobs.txt"

HOST_SYMBOL="EURUSD.dk"     # existing symbol to host the EA chart (any existing one)
TIMEOUT=2400                # max seconds to wait for the import run
CLEAN=0

log() { printf '%s\n' "$*" >&2; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# --- parse args ------------------------------------------------------------
SYMS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --clean)        CLEAN=1; shift ;;
    --host-symbol)  HOST_SYMBOL="$2"; shift 2 ;;
    --timeout)      TIMEOUT="$2"; shift 2 ;;
    -h|--help)      sed -n '3,22p' "$0"; exit 0 ;;
    -*)             die "unknown flag: $1" ;;
    *)              SYMS+=("$1"); shift ;;
  esac
done
[[ ${#SYMS[@]} -ge 1 ]] || die "no symbols given (e.g. ./mt5_import.sh AUDUSD)"
[[ -x "$TERMINAL" ]] || die "terminal64 not found: $TERMINAL"

proc_running() { tasklist.exe /FI "IMAGENAME eq terminal64.exe" 2>/dev/null | grep -qi terminal64.exe; }

# --- 1. refuse to disrupt a running terminal -------------------------------
if proc_running; then
  die "terminal64.exe is already running - refusing to launch (could disrupt the user's terminal). Close MT5 and retry."
fi
log "no terminal64 running - safe to launch."

# --- 2. stage CSVs + build the job list ------------------------------------
mkdir -p "$IMPORT_DIR"
for s in "${SYMS[@]}"; do
  [[ -f "$REPO/data/mt5_ready/$s.csv" ]] || die "missing CSV: data/mt5_ready/$s.csv"
  log "staging $s ..."
  "$STAGE" "$s" >/dev/null || die "staging failed for $s"
done
printf '%s\n' "${SYMS[@]}" > "$JOBS"
rm -f "$STATUS" "$IMPORT_DIR/jobs.done"
log "jobs.txt -> ${SYMS[*]}"

# --- 3. startup config ini (auto-attach AutoImport; NON-portable data dir) --
{
  echo "; Auto-generated by pipeline/mt5_import.sh - one-shot unattended import."
  echo "[StartUp]"
  echo "Expert=AutoImport"
  echo "Symbol=$HOST_SYMBOL"
  echo "Period=H4"
} > "$INI_WSL"
log "config ini -> $INI_WIN (host chart $HOST_SYMBOL)"

# --- 4. launch terminal64 headlessly (self-closes via TerminalClose) -------
log "launching terminal64 /config ..."
START_TS=$(date +%s)
nohup "$TERMINAL" "/config:$INI_WIN" >/dev/null 2>&1 &
sleep 8
if proc_running; then log "terminal64 launched (running)."; else log "WARN: terminal64 not detected after launch."; fi

# --- 5. wait for completion (terminal self-exit or DONE marker) ------------
log "waiting up to ${TIMEOUT}s for import to finish + terminal to self-close ..."
deadline=$(( START_TS + TIMEOUT ))
done_seen=0
timed_out=0
while :; do
  [[ -f "$STATUS" ]] && grep -q '^# DONE' "$STATUS" 2>/dev/null && done_seen=1
  if ! proc_running; then log "terminal64 has exited."; break; fi
  if (( $(date +%s) >= deadline )); then
    log "TIMEOUT after ${TIMEOUT}s - terminal still running; leaving it for the operator to close."
    timed_out=1
    break
  fi
  sleep 5
done
ELAPSED=$(( $(date +%s) - START_TS ))

# --- 6. parse status + report ----------------------------------------------
log "----- import_status.txt -----"
if [[ -f "$STATUS" ]]; then cat "$STATUS" >&2; else log "(no status file was written!)"; fi
log "-----------------------------"
log "wall time: ${ELAPSED}s; DONE marker: $([[ $done_seen -eq 1 ]] && echo yes || echo no); timed_out: $timed_out"

fail=0
for s in "${SYMS[@]}"; do
  if [[ -f "$STATUS" ]] && grep -q "^${s},OK," "$STATUS"; then
    log "  $s: OK"
    [[ $CLEAN -eq 1 ]] && "$STAGE" --clean "$s" >/dev/null 2>&1 && log "    (staged CSV cleaned)"
  else
    log "  $s: FAIL / missing"
    fail=1
  fi
done

rm -f "$INI_WSL"
if (( fail || timed_out )); then die "import did not complete cleanly (see status above)"; fi
log "ALL IMPORTS OK (${#SYMS[@]} symbol(s), ${ELAPSED}s)"
